apiVersion: v1
kind: Pod
metadata:
 name: mongo-pod
 labels:
  name: mongo-pod
  app: microservice-book
spec:
 containers:
 - name: mongo
   image: mongo:latest
   #command:
   #- /bin/bash
   #- -c
   env:
   - name: MONGO_INITDB_ROOT_USERNAME
     value: "ymartinez7"
   - name: MONGO_INITDB_ROOT_PASSWORD
     value: "y18010611m"
   ports:
    - containerPort: 27017