apiVersion: v1
kind: Service
metadata:
 name: mongo-service
 labels:
  name: mongo-service
  app: database
spc:
 type: LoadBalancer
 ports:
  - port: 27017
    targetPort: 27017
 selector:
 app: microservice-book
 name: mongo-pod