apiVersion: apps/v1
kind: Deployment
metadata: 
 name: mongo-deploy
 labels:
  name: mongo-deply
  app: microservice-book
 spec:
  replicas: 1
  selector:
   matchLabels:
    app: microservice-book
    name: mongo-pod
  template:
   metadata:
    name: mongo-pod
    labels:
      app: microservice-book
      name: mongo-pod
   spec:
    containers:
     - name: mongodb
       mage: mongo:4.2.12
       command:
       - /bin/bash
       - -c
       env:
       - name: MONGO_INITDB_USERNAME
         value: "ymartinez7"
       - name: MONGO_INITPASSWORD
         value: "y18010611m"	
         ports:
          - containerPort: 27017