apiVersion: v1
kind: Service
metadata:
 name: gateway-service
 labels:
  name: gateway-service
  app: microserice
spec:
 type: LoadBalancer
 ports:
  - port: 80
    targetPort: 80
    nodePort: 30010
 selector:
    app: gateway
    type: microservice