apiVersion: v1
kind: Service
metadata:
 name: microservice-book-service
 labels:
  name: microservice-book-service
  app: microserice
spec:
 type: ClusterIP
 ports:
  - port: 80
    targetPort: 80
 selector:
  app: microservice-book
  type: microservice