apiVersion: v1
kind: Pod
metadata:
 name: mssqlserver-pod
 labels:
  app: microservice-identity
  name: mssql-pod
spec:
 containers:
 - name: mssql
   image: mcr.microsoft.com/mssql/server
   ports:
   - containerPorts: 1433
   env:
   - name: ACCEPT_EULA
     value: "Y"
   - name: SA_PASSWORD
     value: "y18010611m"